name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: mihails-strasuns/setup-dlang@v1
      name: Install DMD
    - name: Build
      run: dub build
    - name: E2E tests
      run: cd tests && sh run_tests.sh
    - name: Dub tests
      run: dub test --coverage && bash <(curl -s https://codecov.io/bash)

